"""empty message

Revision ID: 05e8dc6ab571
Revises: f7af1fa592c6
Create Date: 2018-02-28 11:34:59.523324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e8dc6ab571'
down_revision = 'f7af1fa592c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'deleted')
    # ### end Alembic commands ###
