"""empty message

Revision ID: 14cfdfb9447a
Revises: aa5f5c5f495f
Create Date: 2018-03-15 10:21:58.770370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cfdfb9447a'
down_revision = 'aa5f5c5f495f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('completed_tz', sa.Integer(), nullable=True))
    op.add_column('survey', sa.Column('declined_tz', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'declined_tz')
    op.drop_column('survey', 'completed_tz')
    # ### end Alembic commands ###
