"""empty message

Revision ID: 15c9dbfaa09f
Revises: 1737fb34d6b6
Create Date: 2018-03-01 12:12:04.499773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c9dbfaa09f'
down_revision = '1737fb34d6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_option', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_option', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_option', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question_option', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
