x-environment: &COMMON_ENVIRONMENT
  ENVIRONMENT: DEVELOPMENT
  ALLOW_DROP_DATA: "true"
  PROXY_URL: http://localhost
  HS_ISSUER: http://localhost/
  HS_KEY: secret
  AUTH0_AUDIENCE: http://localhost/
  AUTH0_CLIENT_ID: dummy
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_PASSWORD: doesntmatter
  LOG_LEVEL: INFO
  LOG_FORMAT: COLOUR

services:
  dhos-questions-integration-tests:
    container_name: "dhos-questions-integration-tests"
    build:
      context: .
    environment:
      <<: *COMMON_ENVIRONMENT
      BEHAVE_ARGS: ${BEHAVE_ARGS:-}
      REPORT_PORTAL_URL: ${REPORT_PORTAL_URL:-}
      REPORT_PORTAL_TOKEN: ${REPORT_PORTAL_TOKEN:-}
      REPORT_PORTAL_PROJECT: ${REPORT_PORTAL_PROJECT:-}
      ENVIRONMENT: ${ENVIRONMENT:-}
      RELEASE: ${RELEASE:-}
    command: >
      bash -c "behave --no-capture --no-logcapture ${BEHAVE_ARGS:-}"
    depends_on:
      "dhos-questions-api":
        condition: service_healthy

  dhos-questions-api:
    container_name: "dhos-questions-api"
    build:
      context: ../
    environment:
      <<: *COMMON_ENVIRONMENT
      DATABASE_HOST: dhos-questions-api-db
      DATABASE_PORT: 5432
      DATABASE_USER: dhos-questions-api
      DATABASE_PASSWORD: dhos-questions-api
      DATABASE_NAME: dhos-questions-api
    command: >
      bash -c "flask db upgrade && python -m dhos_questions_api"
    healthcheck:
      test: curl -f http://localhost:5000/running || false
      interval: 3s
      retries: 40
      start_period: 10s
    depends_on:
      "dhos-questions-api-db":
        condition: service_healthy

  dhos-questions-api-db:
    container_name: "dhos-questions-api-db"
    image: docker.io/postgres
    environment:
      <<: *COMMON_ENVIRONMENT
      POSTGRES_USER: dhos-questions-api
      POSTGRES_PASSWORD: dhos-questions-api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 5s
      retries: 20
