@startuml

skinparam defaultFontName Courier

Class Answer {
    VARCHAR[36]                        ★ uuid                                     
    DATETIME                           ⚪ created                                  
    VARCHAR                            ⚪ created_by_                              
    DATETIME                           ⚪ deleted                                  
    DATETIME                           ⚪ modified                                 
    VARCHAR                            ⚪ modified_by_                             
    VARCHAR                            ⚪ question_id                              
    VARCHAR                            ⚪ survey_id                                
    VARCHAR                            ⚪ text                                     
    VARCHAR                            ⚪ value                                    
    delete()                                                                      
    set_property()                                                                
    to_dict()                                                                     
    INDEX[survey_id,question_id,value] » only_one_active_identical_question_option
}

Class Group {
    VARCHAR[36] ★ uuid        
    DATETIME    ⚪ created     
    VARCHAR     ⚪ created_by_ 
    DATETIME    ⚪ deleted     
    VARCHAR     ⚪ group       
    DATETIME    ⚪ modified    
    VARCHAR     ⚪ modified_by_
    +           question      
    delete()                  
    to_dict()                 
}

Class Question {
    VARCHAR[36] ★ uuid            
    VARCHAR     ☆ question_type_id
    DATETIME    ⚪ created         
    VARCHAR     ⚪ created_by_     
    DATETIME    ⚪ deleted         
    DATETIME    ⚪ modified        
    VARCHAR     ⚪ modified_by_    
    VARCHAR     ⚪ question        
    +           groups            
    +           question_options  
    +           question_type     
    delete()                      
    to_dict()                     
}

Class QuestionOption {
    VARCHAR[36] ★ uuid                   
    VARCHAR     ☆ question_id            
    VARCHAR     ☆ question_option_type_id
    DATETIME    ⚪ created                
    VARCHAR     ⚪ created_by_            
    DATETIME    ⚪ deleted                
    DATETIME    ⚪ modified               
    VARCHAR     ⚪ modified_by_           
    INTEGER     ⚪ order                  
    VARCHAR     ⚪ text                   
    VARCHAR     ⚪ value                  
    +           question_option_type     
    delete()                             
    to_dict()                            
}

Class QuestionOptionType {
    VARCHAR[36] ★ uuid        
    DATETIME    ⚪ created     
    VARCHAR     ⚪ created_by_ 
    DATETIME    ⚪ deleted     
    DATETIME    ⚪ modified    
    VARCHAR     ⚪ modified_by_
    INTEGER     ⚪ value       
    delete()                  
    to_dict()                 
}

Class QuestionType {
    VARCHAR[36] ★ uuid        
    DATETIME    ⚪ created     
    VARCHAR     ⚪ created_by_ 
    DATETIME    ⚪ deleted     
    DATETIME    ⚪ modified    
    VARCHAR     ⚪ modified_by_
    INTEGER     ⚪ value       
    delete()                  
    to_dict()                 
}

Class Survey {
    VARCHAR[36] ★ uuid        
    VARCHAR     ☆ group_id    
    DATETIME    ⚪ completed   
    INTEGER     ⚪ completed_tz
    DATETIME    ⚪ created     
    VARCHAR     ⚪ created_by_ 
    DATETIME    ⚪ declined    
    INTEGER     ⚪ declined_tz 
    DATETIME    ⚪ deleted     
    DATETIME    ⚪ modified    
    VARCHAR     ⚪ modified_by_
    VARCHAR     ⚪ user_id     
    VARCHAR     ⚪ user_type   
    +           group         
    delete()                  
    to_dict()                 
}

Question <--o QuestionType: question_type_id

QuestionOption <--o Question: question_id

QuestionOption <--o QuestionOptionType: question_option_type_id

Survey <--o Group: group_id

right footer generated by sadisplay v0.4.9

@enduml
